spring:
  application:
    name: product-service
  datasource:
    url: ${PRODUCT_SERVICE_DB_URL}
    username: ${PRODUCT_SERVICE_DB_USERNAME}
    password: ${PRODUCT_SERVICE_DB_PASSWORD}
  jpa:
    ddl-auto: validate

payment-service:
  url: ${no_default_value_payment-service}